const translations = {
  fr: {
    nav_home: "Accueil",
    nav_about: "À propos",
    nav_services: "Services",
    nav_team: "Équipe",
    nav_testimonials: "Témoignages",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    home_title: "Bienvenue sur O’PP MANAGER",
    home_text: "Votre solution pour la vente professionnelle.",
    about_title: "À propos",
    about_text: "Nous aidons les entreprises à mieux vendre grâce à une plateforme intuitive et puissante.",
    services_title: "Nos Services",
    service_1: "Gestion des ventes",
    service_2: "Suivi client",
    service_3: "Analyse de performance",
    team_title: "Notre Équipe",
    team_text: "Une équipe passionnée par la réussite commerciale.",
    testimonials_title: "Témoignages",
    testimonial_1: "Une plateforme exceptionnelle pour booster nos ventes !",
    faq_title: "Foire Aux Questions",
    faq_q1: "Comment commencer ?",
    faq_a1: "Créez un compte et commencez à ajouter vos produits.",
    contact_title: "Contactez-nous",
    send: "Envoyer",
  },
  en: {
    nav_home: "Home",
    nav_about: "About",
    nav_services: "Services",
    nav_team: "Team",
    nav_testimonials: "Testimonials",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    home_title: "Welcome to O’PP MANAGER",
    home_text: "Your professional sales solution.",
    about_title: "About Us",
    about_text: "We help businesses sell better with a powerful, intuitive platform.",
    services_title: "Our Services",
    service_1: "Sales Management",
    service_2: "Customer Tracking",
    service_3: "Performance Analytics",
    team_title: "Our Team",
    team_text: "A passionate team focused on your business success.",
    testimonials_title: "Testimonials",
    testimonial_1: "An amazing platform that boosted our sales!",
    faq_title: "Frequently Asked Questions",
    faq_q1: "How to start?",
    faq_a1: "Create an account and start adding your products.",
    contact_title: "Contact Us",
    send: "Send",
  },
  es: {
    nav_home: "Inicio",
    nav_about: "Sobre Nosotros",
    nav_services: "Servicios",
    nav_team: "Equipo",
    nav_testimonials: "Testimonios",
    nav_faq: "FAQ",
    nav_contact: "Contacto",
    home_title: "Bienvenido a O’PP MANAGER",
    home_text: "Tu solución profesional de ventas.",
    about_title: "Sobre Nosotros",
    about_text: "Ayudamos a las empresas a vender mejor con una plataforma poderosa e intuitiva.",
    services_title: "Nuestros Servicios",
    service_1: "Gestión de Ventas",
    service_2: "Seguimiento de Clientes",
    service_3: "Análisis de Rendimiento",
    team_title: "Nuestro Equipo",
    team_text: "Un equipo apasionado por tu éxito comercial.",
    testimonials_title: "Testimonios",
    testimonial_1: "¡Una plataforma increíble para aumentar nuestras ventas!",
    faq_title: "Preguntas Frecuentes",
    faq_q1:
